### ISSUE TITLE
An "unwhitelist" item appears in the tab context menu

### ISSUE THREAD

**Issue by THWeng** [darktrojan/badge#17]
This tab context menu item ("unwhitelist") occures when a tab that does not contain web content (e.g. Preferences tab, New tab, Add-ons tab, etc.), as the attached image shows.
This does not cause any trouble in my usage, but sometimes it's a little annoying.
![tab_badge_bug](https://cloud.githubusercontent.com/assets/14852275/10122243/b19ba194-6544-11e5-919b-48efce9b74f6.png)

**Comment by darktrojan** [comment]
That was easy, thank you for reporting it!
